name: paper-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build document
        run: |
          make -C manuscript
      - name: Upload main PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: manuscript/build/main.pdf
      - name: Upload SI PDF
        uses: actions/upload-artifact@v2
        with:
          name: si.pdf
          path: manuscript/build/si.pdf
      - name: Upload plots as PDFs
        uses: actions/upload-artifact@v2
        with:
          name: plots
          path: manuscript/build/figures/*.pdf
